---
layout: cv
title: "Samantha Powell's Resume"
---

# Samantha Powell
Business Analytics Student

<div id="webaddress">
<a href="mailto:skpowell38@gmail.com">skpowell38@gmail.com</a>  
Phone: 713-775-6080
</div>

## Education

**Dulles High School**  
*Houston, TX*  
**High School Diploma**  
_June 2020_

**Brigham Young University - Idaho**  
*Rexburg, ID*  
**Business Analytics**  
_September 2020 - April 2025_	

# Academic Profile 

**CSE 110-Programming Building Blocks**  
September 2022 - December 2022
Learned programming fundamentals, including variables, loops, and conditionals, to solve practical problems. Gained confidence in applying programming skills across diverse domains.				

**CIT 111-Introduction to Databases**  
September 2023 - December 2023
Learned fundamental database concepts, including relational models and joins. Designed, created, and queried databases using database management system software.				

**CSE 111-Programming with functions**  
September 2023 - December 2023
Enhanced programming skills by writing and debugging functions and utilizing external libraries. Developed proficiency in error handling and solving interdisciplinary problems with code.				

**CIT 381-Business Intel and Analytics**  
January 2024 - April 2024
Learned data storage, retrieval, and analysis techniques to support business decision-making. Gained skills in data mining, visualization, and automation of analytics processes for strategic insights.				

**DS 250-Data Science Programming**  
September 2024 - December 2024
Learned to write programs for data retrieval, preparation, and analysis using data science libraries. Applied machine learning techniques to make predictions and created visualizations for insights.				

---
## Work Experience

### Dog Sitting  
*Houston, TX*  

- Provided dog-sitting services for a neighboring family.
- Ensured the well-being of the dog by letting it out, feeding it, and maintaining water levels.
- Returned in the evenings to feed the dog and secure it in its designated area within the house.

### LDS Helping Hands  
*Sugar Land, TX*  
**Hurricane Clean-Up Volunteer**  
_May 2018 - May 2020_

- Participated in multiple groups engaged in tearing down drywall in houses affected by Hurricane Harvey.
- Assisted in the removal of items from flooded houses as directed by homeowners.

### Babysitter  
*Sugar Land, TX*  
_August 2017 - August 2017_

---

## Skills

1. **Organizational Skills**  
   - Proficient in executing tasks once specific instructions are provided.

2. **Interpersonal Skills**  
   - Effectively interacts with others and maintains a calm demeanor in various situations.

3. **Communication Skills**  
   - Communicates clearly and succinctly, striving for straightforward communication.

<!-- Footer -->
<!-- Last updated: October 2024 -->
